const mongoose=require('mongoose');
const {Schema,model}=mongoose;
const options={timestamps:true,versionKey:'version'};
const Conversation=model('Conversation',new Schema({kind:{type:String,enum:['support','seller'],required:true},members:[{type:Schema.Types.ObjectId,ref:'User'}],seller:{type:Schema.Types.ObjectId,ref:'Seller'},lastMessageAt:{type:Date,default:Date.now}},options));
Conversation.schema.index({members:1,lastMessageAt:-1,_id:-1});
Conversation.schema.index({kind:1,lastMessageAt:-1,_id:-1});
const Message=model('Message',new Schema({conversation:{type:Schema.Types.ObjectId,ref:'Conversation',required:true,index:true},sender:{type:Schema.Types.ObjectId,ref:'User',required:true},body:{type:String,default:'',maxlength:4000},attachments:[{mediaId:{type:Schema.Types.ObjectId,ref:'Media'},uri:String,mime:String}],deliveredTo:[{type:Schema.Types.ObjectId,ref:'User'}],readBy:[{type:Schema.Types.ObjectId,ref:'User'}]},options));
Message.schema.index({conversation:1,createdAt:-1,_id:-1});
const Activity=model('Activity',new Schema({user:{type:Schema.Types.ObjectId,ref:'User',required:true,index:true},campaign:{type:Schema.Types.ObjectId,ref:'NotificationCampaign'},category:{type:String,enum:['chat','order','alert','promo'],required:true},title:String,body:String,target:Schema.Types.Mixed,readAt:Date,pushStatus:{type:String,enum:['pending','sent','skipped','failed'],default:'pending',index:true},pushAttempts:{type:Number,default:0,min:0},pushLastAttemptAt:Date},options));
Activity.schema.index({user:1,_id:-1});
Activity.schema.index({user:1,category:1,_id:-1});
Activity.schema.index({pushStatus:1,pushAttempts:1,createdAt:1});
Activity.schema.index({user:1,campaign:1},{unique:true,partialFilterExpression:{campaign:{$type:'objectId'}}});
const deviceTokenSchema=new Schema({user:{type:Schema.Types.ObjectId,ref:'User',required:true,index:true},installationId:{type:String,required:true,maxlength:200},platform:{type:String,enum:['android','ios'],required:true},tokenHash:{type:String,required:true,unique:true},tokenCiphertext:{type:String,required:true,select:false},tokenIv:{type:String,required:true,select:false},tokenTag:{type:String,required:true,select:false},appBuild:{type:String,maxlength:50},enabled:{type:Boolean,default:true,index:true},lastSeenAt:{type:Date,default:Date.now}},options);deviceTokenSchema.index({user:1,installationId:1},{unique:true});deviceTokenSchema.index({user:1,enabled:1,lastSeenAt:-1});
const DeviceToken=model('DeviceToken',deviceTokenSchema);
module.exports={Conversation,Message,Activity,DeviceToken};
