const crypto=require('node:crypto');
const mongoose=require('mongoose');
const {Product}=require('../models/catalog.model');
const {User,Seller}=require('../models/account.model');
const {AffiliateLink,AffiliateAttribution}=require('../models/marketing.model');
const {BusinessRule,LedgerAccount,LedgerEntry,AuditEvent}=require('../models/system.model');
const {Activity}=require('../models/communication.model');
const {AppError,badRequest,notFound,conflict}=require('../utils/errors');
const {configuredFeatureAvailable,validateBusinessRule}=require('./business-rule.service');
const code=()=>`AF${crypto.randomBytes(6).toString('hex').toUpperCase()}`;
async function rule(required=true){if(!await configuredFeatureAvailable('affiliate','affiliate')){if(required)throw new AppError(503,'PROVIDER_UNAVAILABLE','Affiliate earning is not available yet.');return null;}const row=await BusinessRule.findOne({key:'affiliate',enabled:true}).lean();return validateBusinessRule('affiliate',true,row.data);}
async function createLink({owner,productId}){const policy=await rule(),[affiliate,product]=await Promise.all([User.findOne({_id:owner,accountType:{$ne:'seller'},suspended:false}),Product.findOne({_id:productId,status:'approved'})]);if(!affiliate)throw badRequest('A personal account is required for affiliate links.');if(!product||!await Seller.exists({_id:product.seller,status:'approved'}))throw notFound('Product unavailable.');let link=await AffiliateLink.findOne({owner,product:product._id});if(!link){for(let i=0;i<5&&!link;i++){try{link=await AffiliateLink.create({owner,product:product._id,code:code()});}catch(error){if(error?.code!==11000)throw error;link=await AffiliateLink.findOne({owner,product:product._id});}}}return {id:String(link._id),code:link.code,productId:String(product._id),title:product.title,priceMinor:product.priceMinor,commissionPercent:policy.commissionPercent,estimatedCommissionMinor:Math.floor(product.priceMinor*policy.commissionPercent/100),clicks:link.clicks};}
async function recordClick(value){const link=await AffiliateLink.findOneAndUpdate({code:String(value).toUpperCase(),enabled:true},{$inc:{clicks:1}},{new:true});return Boolean(link);}
async function affiliateCenter(owner){const policy=await rule(),links=await AffiliateLink.find({owner,enabled:true}).populate('product').sort({createdAt:-1}).lean(),rows=await AffiliateAttribution.find({owner}).sort({createdAt:-1}).limit(100).lean();return {rule:policy,clicks:links.reduce((sum,row)=>sum+row.clicks,0),orders:rows.length,pendingMinor:rows.filter(row=>row.status==='pending').reduce((sum,row)=>sum+row.commissionMinor-row.reversedMinor,0),earnedMinor:rows.filter(row=>row.status==='released').reduce((sum,row)=>sum+row.commissionMinor-row.reversedMinor,0),links:links.filter(row=>row.product).map(row=>({id:String(row._id),code:row.code,productId:String(row.product._id),title:row.product.title,priceMinor:row.product.priceMinor,estimatedCommissionMinor:Math.floor(row.product.priceMinor*policy.commissionPercent/100),clicks:row.clicks}))};}
async function attributeOrder({owner,order,lines,affiliateCode,session}){if(!affiliateCode)return null;const policy=await rule(),link=await AffiliateLink.findOne({code:String(affiliateCode).toUpperCase(),enabled:true}).session(session);if(!link)throw badRequest('Affiliate link is invalid or unavailable.');if(String(link.owner)===String(owner))throw badRequest('You cannot earn from your own purchase.');const grossMinor=lines.filter(line=>String(line.product._id)===String(link.product)).reduce((sum,line)=>sum+line.product.priceMinor*line.qty,0);if(!grossMinor)throw badRequest('The affiliate product is not in this checkout.');const commissionMinor=Math.floor(grossMinor*policy.commissionPercent/100);if(!commissionMinor)return null;const [row]=await AffiliateAttribution.create([{link:link._id,owner:link.owner,buyer:owner,order:order._id,code:link.code,grossMinor,commissionMinor,ratePercent:policy.commissionPercent,releaseAfterDays:policy.releaseAfterDays,status:'attributed'}],{session});return row;}
async function account(owner,session){return LedgerAccount.findOneAndUpdate({owner,kind:'pending_earnings',currency:'BDT'},{$setOnInsert:{owner,kind:'pending_earnings',currency:'BDT'},$inc:{version:1}},{upsert:true,new:true,session});}
async function qualifyAffiliate(order,session){const row=await AffiliateAttribution.findOne({order:order._id,status:'attributed'}).session(session);if(!row)return false;const returnDays=Math.max(0,...order.lines.map(line=>Number(line.returnDays)||0));row.status='pending';row.eligibleAt=new Date(Date.now()+Math.max(row.releaseAfterDays,returnDays)*86400000);await row.save({session});const ledger=await account(row.owner,session);await LedgerEntry.create([{account:ledger._id,amountMinor:row.commissionMinor,reference:`affiliate:${row._id}:pending`,metadata:{title:'Affiliate commission pending',affiliateId:String(row._id),orderId:String(order._id)}}],{session});return true;}
async function releaseAffiliate(id){return mongoose.connection.transaction(async session=>{const row=await AffiliateAttribution.findOne({_id:id,status:'pending',eligibleAt:{$lte:new Date()}}).session(session);if(!row)return false;const remaining=row.commissionMinor-row.reversedMinor;if(remaining>0){const pending=await account(row.owner,session),earnings=await LedgerAccount.findOneAndUpdate({owner:row.owner,kind:'earnings',currency:'BDT'},{$setOnInsert:{owner:row.owner,kind:'earnings',currency:'BDT'},$inc:{version:1}},{upsert:true,new:true,session});await LedgerEntry.create([{account:pending._id,amountMinor:-remaining,reference:`affiliate:${row._id}:pending:release`,metadata:{title:'Affiliate commission released'}},{account:earnings._id,amountMinor:remaining,reference:`affiliate:${row._id}:earnings:release`,metadata:{title:'Affiliate commission available'}}],{session,ordered:true});}row.status='released';row.releasedAt=new Date();await row.save({session});await Activity.create([{user:row.owner,category:'promo',title:'Affiliate commission available',body:'Your affiliate earning is ready to withdraw.',target:{affiliateId:String(row._id),orderId:String(row.order)}}],{session});return true;});}
async function reverseAffiliate({order,request,fullRefund,session}){const row=await AffiliateAttribution.findOne({order:order._id,status:{$in:['attributed','pending','released']}}).session(session);if(!row)return false;if(row.status==='attributed'){if(fullRefund){row.status='reversed';row.reversedMinor=row.commissionMinor;row.reversedAt=new Date();await row.save({session});}return fullRefund;}const remaining=row.commissionMinor-row.reversedMinor;if(!remaining)return false;const paid=order.payment?.amountMinor||order.totalMinor||1,amount=fullRefund?remaining:Math.min(remaining,Math.floor(row.commissionMinor*request.amountMinor/paid));if(amount<1)return false;const kind=row.status==='released'?'earnings':'pending_earnings',ledger=await LedgerAccount.findOneAndUpdate({owner:row.owner,kind,currency:'BDT'},{$setOnInsert:{owner:row.owner,kind,currency:'BDT'},$inc:{version:1}},{upsert:true,new:true,session});await LedgerEntry.create([{account:ledger._id,amountMinor:-amount,reference:`affiliate:${row._id}:return:${request._id}`,metadata:{title:'Affiliate commission reversed',orderId:String(order._id)}}],{session});row.reversedMinor+=amount;if(row.reversedMinor>=row.commissionMinor){row.status='reversed';row.reversedAt=new Date();}await row.save({session});return true;}
async function cancelAffiliate(order,session){const row=await AffiliateAttribution.findOne({order:order._id,status:'attributed'}).session(session);if(!row)return false;row.status='reversed';row.reversedMinor=row.commissionMinor;row.reversedAt=new Date();await row.save({session});return true;}
async function listAdminAffiliates(query={}){
  const limit=Math.min(100,Math.max(1,Number(query.limit)||50)),offset=Math.max(0,Number(query.offset)||0),filter={};
  if(query.enabled==='true'||query.enabled==='false')filter.enabled=query.enabled==='true';
  const links=await AffiliateLink.find(filter).populate('owner','name email phone').populate('product','title status').sort({createdAt:-1,_id:-1}).skip(offset).limit(limit+1);
  const ids=links.slice(0,limit).map(row=>row._id),totals=ids.length?await AffiliateAttribution.aggregate([{$match:{link:{$in:ids}}},{$group:{_id:'$link',orders:{$sum:1},grossMinor:{$sum:'$grossMinor'},commissionMinor:{$sum:'$commissionMinor'},reversedMinor:{$sum:'$reversedMinor'},pendingMinor:{$sum:{$cond:[{$eq:['$status','pending']},{$subtract:['$commissionMinor','$reversedMinor']},0]}},releasedMinor:{$sum:{$cond:[{$eq:['$status','released']},{$subtract:['$commissionMinor','$reversedMinor']},0]}}}}]):[];
  const byId=new Map(totals.map(row=>[String(row._id),row]));
  return {items:links.slice(0,limit).map(row=>{const total=byId.get(String(row._id))||{};return {id:String(row._id),name:row.owner?.name||'Unavailable affiliate',email:row.owner?.email,phone:row.owner?.phone,code:row.code,title:row.product?.title||'Unavailable product',productStatus:row.product?.status,clicks:row.clicks,orders:total.orders||0,grossMinor:total.grossMinor||0,commissionMinor:total.commissionMinor||0,reversedMinor:total.reversedMinor||0,pendingMinor:total.pendingMinor||0,releasedMinor:total.releasedMinor||0,enabled:row.enabled,status:row.enabled?'enabled':'disabled',version:row.version,createdAt:row.createdAt};}),nextOffset:links.length>limit?offset+limit:null};
}
async function updateAffiliateLink({id,input,actor}){
  if(!mongoose.isValidObjectId(id))throw notFound('Affiliate link not found.');
  const link=await AffiliateLink.findOne({_id:id,version:input.version});if(!link)throw conflict('Affiliate link changed. Refresh and try again.');
  link.enabled=input.enabled;await link.save();await AuditEvent.create({actor,action:input.enabled?'affiliate.enable':'affiliate.disable',target:String(link._id),reason:input.reason,metadata:{code:link.code,owner:String(link.owner),product:String(link.product)}});
  return {id:String(link._id),enabled:link.enabled,status:link.enabled?'enabled':'disabled',version:link.version};
}
async function processDueAffiliates(){const rows=await AffiliateAttribution.find({status:'pending',eligibleAt:{$lte:new Date()}}).select('_id').limit(100).lean();let processed=0,failed=0;for(const row of rows){try{if(await releaseAffiliate(row._id))processed++;}catch{failed++;}}return {processed,failed};}
module.exports={createLink,recordClick,affiliateCenter,attributeOrder,qualifyAffiliate,releaseAffiliate,reverseAffiliate,cancelAffiliate,processDueAffiliates,listAdminAffiliates,updateAffiliateLink};
