const mongoose=require('mongoose');
const {PaymentMethod}=require('../models/account.model');
const {AppError,badRequest,notFound}=require('../utils/errors');
const configured=()=>Boolean(process.env.PAYMENT_METHOD_BRIDGE_ENDPOINT?.startsWith('https://')&&process.env.PAYMENT_METHOD_BRIDGE_TOKEN);
const json=row=>({id:String(row._id),provider:row.provider,type:row.type,brand:row.brand||'',lastFour:row.lastFour||'',phoneLastFour:row.phoneLastFour||'',expiryMonth:row.expiryMonth,expiryYear:row.expiryYear,isDefault:row.isDefault,createdAt:row.createdAt});
async function bridge(action,payload){if(!configured())throw new AppError(503,'PROVIDER_UNAVAILABLE','Saved online payment methods are not available yet.');let response;try{response=await fetch(process.env.PAYMENT_METHOD_BRIDGE_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${process.env.PAYMENT_METHOD_BRIDGE_TOKEN}`},body:JSON.stringify({action,...payload}),signal:AbortSignal.timeout(10000)});}catch{throw new AppError(503,'PROVIDER_UNAVAILABLE','Payment provider could not be reached.');}let data={};try{data=await response.json();}catch{}if(!response.ok)throw new AppError(502,'PROVIDER_ERROR','Payment provider rejected the request.');return data;}
async function list(owner){return (await PaymentMethod.find({user:owner}).sort({isDefault:-1,createdAt:-1})).map(json);}
async function attach({owner,input}){const data=await bridge('tokenize',{providerToken:input.providerToken});if(!['card','mobile_wallet'].includes(data.type)||!String(data.provider||'').match(/^[a-z0-9_-]{2,50}$/i)||String(data.customerRef||'').length<3||String(data.methodRef||'').length<3)throw new AppError(502,'PROVIDER_ERROR','Payment provider returned an invalid method reference.');if(data.type==='card'&&!/^\d{4}$/.test(String(data.lastFour||'')))throw new AppError(502,'PROVIDER_ERROR','Payment provider returned invalid card metadata.');if(data.type==='mobile_wallet'&&!/^\d{4}$/.test(String(data.phoneLastFour||'')))throw new AppError(502,'PROVIDER_ERROR','Payment provider returned invalid wallet metadata.');return mongoose.connection.transaction(async session=>{const exists=await PaymentMethod.exists({user:owner}).session(session);const [row]=await PaymentMethod.create([{user:owner,provider:data.provider,providerCustomerRef:data.customerRef,providerMethodRef:data.methodRef,type:data.type,brand:String(data.brand||'').slice(0,50),lastFour:data.lastFour,phoneLastFour:data.phoneLastFour,expiryMonth:data.expiryMonth,expiryYear:data.expiryYear,isDefault:input.isDefault||!exists}],{session});if(row.isDefault)await PaymentMethod.updateMany({user:owner,_id:{$ne:row._id}},{$set:{isDefault:false}},{session});return json(row);});}
async function makeDefault({owner,id}){return mongoose.connection.transaction(async session=>{const row=await PaymentMethod.findOne({_id:id,user:owner}).session(session);if(!row)throw notFound('Payment method not found.');await PaymentMethod.updateMany({user:owner},{$set:{isDefault:false}},{session});row.isDefault=true;await row.save({session});return json(row);});}
async function remove({owner,id}){const row=await PaymentMethod.findOne({_id:id,user:owner});if(!row)throw notFound('Payment method not found.');await bridge('detach',{provider:row.provider,customerRef:row.providerCustomerRef,methodRef:row.providerMethodRef});await mongoose.connection.transaction(async session=>{await PaymentMethod.deleteOne({_id:row._id,user:owner},{session});if(row.isDefault){const next=await PaymentMethod.findOne({user:owner}).sort({createdAt:-1}).session(session);if(next){next.isDefault=true;await next.save({session});}}});return {ok:true};}
module.exports={configured,list,attach,makeDefault,remove};
