const crypto=require('node:crypto');
const {DeviceToken,Activity}=require('../models/communication.model');
const {User}=require('../models/account.model');
const {AppError}=require('../utils/errors');
function key(){const raw=process.env.PUSH_TOKEN_ENCRYPTION_KEY||'';const value=/^[a-f0-9]{64}$/i.test(raw)?Buffer.from(raw,'hex'):Buffer.from(raw,'base64');return value.length===32?value:null;}
function configured(){return Boolean(process.env.PUSH_CLIENT_ENABLED==='true'&&process.env.PUSH_BRIDGE_ENDPOINT?.startsWith('https://')&&process.env.PUSH_BRIDGE_TOKEN&&key());}
function encrypt(value){const secret=key();if(!secret)throw new AppError(503,'PROVIDER_UNAVAILABLE','Push notifications are not available yet.');const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',secret,iv),ciphertext=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return {tokenCiphertext:ciphertext.toString('base64'),tokenIv:iv.toString('base64'),tokenTag:cipher.getAuthTag().toString('base64')};}
function decrypt(row){const decipher=crypto.createDecipheriv('aes-256-gcm',key(),Buffer.from(row.tokenIv,'base64'));decipher.setAuthTag(Buffer.from(row.tokenTag,'base64'));return Buffer.concat([decipher.update(Buffer.from(row.tokenCiphertext,'base64')),decipher.final()]).toString('utf8');}
const hash=value=>crypto.createHash('sha256').update(value).digest('hex');
async function register({owner,input}){if(!configured())throw new AppError(503,'PROVIDER_UNAVAILABLE','Push notifications are not available yet.');const encrypted=encrypt(input.token),tokenHash=hash(input.token),now=new Date();const existingByToken=await DeviceToken.findOne({tokenHash});if(existingByToken&&(String(existingByToken.user)!==String(owner)||existingByToken.installationId!==input.installationId))await DeviceToken.deleteOne({_id:existingByToken._id});const row=await DeviceToken.findOneAndUpdate({user:owner,installationId:input.installationId},{$set:{platform:input.platform,tokenHash,...encrypted,appBuild:input.appBuild,enabled:true,lastSeenAt:now}},{upsert:true,new:true});return {id:String(row._id),platform:row.platform,installationId:row.installationId,enabled:row.enabled,lastSeenAt:row.lastSeenAt};}
async function unregister({owner,installationId}){await DeviceToken.deleteOne({user:owner,installationId});return {ok:true};}
async function processPushQueue(){if(!configured())return {processed:0,failed:0};const cutoff=new Date(Date.now()-24*60*60*1000),rows=await Activity.find({pushStatus:{$in:['pending','failed']},pushAttempts:{$lt:5},createdAt:{$gte:cutoff}}).sort({createdAt:1}).limit(100);let processed=0,failed=0;for(const activity of rows){try{const user=await User.findById(activity.user).lean();if(user?.preferences?.push===false){activity.pushStatus='skipped';await activity.save();continue;}const devices=await DeviceToken.find({user:activity.user,enabled:true}).select('+tokenCiphertext +tokenIv +tokenTag').limit(20);if(!devices.length){activity.pushStatus='skipped';await activity.save();continue;}const response=await fetch(process.env.PUSH_BRIDGE_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${process.env.PUSH_BRIDGE_TOKEN}`},body:JSON.stringify({tokens:devices.map(decrypt),notification:{title:activity.title||'Loveraf',body:activity.body||''},data:activity.target||{}}),signal:AbortSignal.timeout(10000)});if(!response.ok)throw new Error('Push provider rejected request.');activity.pushStatus='sent';activity.pushAttempts+=1;activity.pushLastAttemptAt=new Date();await activity.save();processed++;}catch{activity.pushStatus='failed';activity.pushAttempts+=1;activity.pushLastAttemptAt=new Date();await activity.save().catch(()=>{});failed++;}}return {processed,failed};}
module.exports={configured,register,unregister,processPushQueue};
