const {test}=require('node:test');
const assert=require('node:assert/strict');
const mongoose=require('mongoose');
const {MongoMemoryReplSet}=require('mongodb-memory-server');
const {ReturnRequest,Order}=require('../models/commerce.model');
const {Product,Inventory}=require('../models/catalog.model');
const {AuditEvent,LedgerAccount,LedgerEntry}=require('../models/system.model');
const {transitionReturn}=require('../services/after-sales.service');
const {aggregateBalance}=require('../services/promo.service');

test('refund evidence, finance permissions and inspected stock remain consistent',async()=>{
  const replica=await MongoMemoryReplSet.create({replSet:{count:1}});
  try{
    await mongoose.connect(replica.getUri('after_sales_test'));
    await Promise.all([ReturnRequest.init(),Order.init(),Product.init(),Inventory.init(),AuditEvent.init(),LedgerAccount.init(),LedgerEntry.init()]);
    const actor=new mongoose.Types.ObjectId(),seller=new mongoose.Types.ObjectId();
    const product=await Product.create({seller,title:'Shirt',sku:'TEST-RETURN',priceMinor:10000,stock:6,soldUnits:4});
    const inventory=await Inventory.create({product:product._id,color:'Blue',size:'M',stock:6});
    const paidOrder=await Order.create({user:actor,totalMinor:40000,paymentMethod:'cod',payment:{status:'paid',amountMinor:40000},sellerOrders:[{seller,status:'delivered'}],lines:[]});
    const create=()=>ReturnRequest.create({user:actor,order:paidOrder._id,seller,type:'return',reason:'Wrong item received',status:'in_transit',amountMinor:20000,refundDestination:{method:'bank',account:'test-account'},lines:[{orderLine:new mongoose.Types.ObjectId(),product:product._id,inventory:inventory._id,color:'Blue',size:'M',qty:2,unitMinor:10000}]});
    const first=await create();
    const common={id:first.id,actor,reason:'Inspected the returned parcel.',roles:['support'],version:0};
    await assert.rejects(transitionReturn({...common,status:'received'}),/suitable for resale/);
    const receipt=await transitionReturn({...common,status:'received',restock:true});
    assert.equal(receipt.receipt.restocked,true);
    assert.equal((await Inventory.findById(inventory.id)).stock,8);
    assert.equal((await Product.findById(product.id)).stock,8);
    const refund={...common,status:'refunded',version:receipt.version,settlement:{method:'bank',reference:'BANK-REFUND-001',amountMinor:20000,paidAt:new Date().toISOString()}};
    await assert.rejects(transitionReturn(refund),/Finance permission/);
    await assert.rejects(transitionReturn({...refund,roles:['finance'],settlement:undefined}),/payment reference/);
    await assert.rejects(transitionReturn({...refund,roles:['finance'],settlement:{...refund.settlement,amountMinor:1}}),/approved amount/);
    const outcomes=await Promise.allSettled([transitionReturn({...refund,roles:['finance']}),transitionReturn({...refund,roles:['finance']})]);
    assert.equal(outcomes.filter(result=>result.status==='fulfilled').length,1);
    assert.equal((await Inventory.findById(inventory.id)).stock,8);
    assert.equal((await Product.findById(product.id).select('+soldUnits')).soldUnits,2);
    const saved=await ReturnRequest.findById(first.id);
    assert.equal(saved.settlement.reference,'BANK-REFUND-001');
    assert.equal(saved.status,'refunded');
    assert.equal((await Order.findById(paidOrder.id)).payment.status,'partially_refunded');
    assert.equal((await Order.findById(paidOrder.id)).payment.refundedMinor,20000);
    assert.equal(await AuditEvent.countDocuments({target:first.id,action:'return.refunded'}),1);
    const second=await create();
    const damaged=await transitionReturn({...common,id:second.id,status:'received',restock:false});
    assert.equal((await Inventory.findById(inventory.id)).stock,8);
    await assert.rejects(transitionReturn({...refund,id:second.id,version:damaged.version,roles:['finance'],settlement:{...refund.settlement,paidAt:new Date().toISOString()}}),error=>error.code===11000);
    assert.equal((await ReturnRequest.findById(second.id)).status,'received');
    assert.equal((await Product.findById(product.id).select('+soldUnits')).soldUnits,2);
    await transitionReturn({...refund,id:second.id,version:damaged.version,roles:['finance'],settlement:{...refund.settlement,reference:'BANK-REFUND-002',paidAt:new Date().toISOString()}});
    assert.equal((await Product.findById(product.id).select('+soldUnits')).soldUnits,0);
    assert.equal((await Inventory.findById(inventory.id)).stock,8);
    assert.equal((await Order.findById(paidOrder.id)).payment.status,'refunded');
    assert.equal((await Order.findById(paidOrder.id)).payment.refundedMinor,40000);
    const promoProduct=await Product.create({seller,title:'Promo item',sku:'TEST-PROMO-RETURN',priceMinor:10000,stock:2,soldUnits:1});
    const promoInventory=await Inventory.create({product:promoProduct._id,color:'Red',size:'M',stock:2});
    const promoAccount=await LedgerAccount.create({owner:actor,kind:'promo'});
    await LedgerEntry.create([{account:promoAccount._id,amountMinor:1000,reference:'promo:return:test:grant'},{account:promoAccount._id,amountMinor:-1000,reference:'promo:return:test:consume'}]);
    const promoOrder=await Order.create({user:actor,subtotalMinor:10000,discountMinor:1000,feeMinor:400,totalMinor:9400,pricingSnapshot:{subtotalMinor:10000,discountMinor:1000,deliveryMinor:0,feeMinor:400,totalMinor:9400},promo:{account:promoAccount._id,usedMinor:1000,refundedMinor:0},paymentMethod:'cod',payment:{status:'paid',amountMinor:9400},sellerOrders:[{seller,status:'delivered'}],lines:[]});
    const sellerPayable=await LedgerAccount.create({owner:new mongoose.Types.ObjectId(),kind:'seller_payable'});
    await LedgerEntry.create({account:sellerPayable._id,amountMinor:8100,reference:`seller-order:${promoOrder.id}:${seller}:payable`,metadata:{grossMinor:9000,platformFeeMinor:900,platformFeePercent:10}});
    const promoReturn=await ReturnRequest.create({user:actor,order:promoOrder._id,seller,type:'return',reason:'Promo item returned',status:'received',amountMinor:9000,promoRestoreMinor:1000,refundDestination:{method:'bank',account:'test-account'},lines:[{orderLine:new mongoose.Types.ObjectId(),product:promoProduct._id,inventory:promoInventory._id,color:'Red',size:'M',qty:1,unitMinor:10000}]});
    await transitionReturn({id:promoReturn.id,status:'refunded',version:0,actor,roles:['finance'],reason:'Promo return reconciled.',settlement:{method:'bank',reference:'PROMO-REFUND-001',amountMinor:9000,paidAt:new Date().toISOString()}});
    assert.equal(await aggregateBalance(promoAccount),1000);
    assert.equal((await Order.findById(promoOrder.id)).promo.refundedMinor,1000);
    assert.equal(await LedgerEntry.countDocuments({reference:`promo:return:${promoReturn.id}:restore`}),1);
    const savedPromoReturn=await ReturnRequest.findById(promoReturn.id);
    assert.equal(savedPromoReturn.sellerPayableReversalMinor,8100);
    const payableEntries=await LedgerEntry.find({account:sellerPayable._id}).lean();
    assert.equal(payableEntries.reduce((sum,item)=>sum+item.amountMinor,0),0);
    assert.equal(await LedgerEntry.countDocuments({reference:`seller-return:${promoReturn.id}:reverse`}),1);
    const unpaidOrder=await Order.create({user:actor,totalMinor:10000,paymentMethod:'cod',payment:{status:'pending'},sellerOrders:[{seller,status:'delivered'}],lines:[]});
    const unpaid=await ReturnRequest.create({user:actor,order:unpaidOrder._id,seller,type:'return',reason:'Wrong item received',status:'received',amountMinor:10000,refundDestination:{method:'bank',account:'test-account'},lines:[{orderLine:new mongoose.Types.ObjectId(),product:product._id,inventory:inventory._id,color:'Blue',size:'M',qty:1,unitMinor:10000}]});
    await assert.rejects(transitionReturn({id:unpaid.id,status:'refunded',version:0,actor,roles:['finance'],reason:'Refund attempted.',settlement:{method:'bank',reference:'UNPAID-REFUND-001',amountMinor:10000,paidAt:new Date().toISOString()}}),/completed payment collection/);
    assert.equal((await ReturnRequest.findById(unpaid.id)).status,'received');
    const exchange=await ReturnRequest.create({user:actor,order:new mongoose.Types.ObjectId(),seller,type:'exchange',reason:'Size needs exchange',status:'in_transit',amountMinor:20000,lines:[{orderLine:new mongoose.Types.ObjectId(),product:product._id,inventory:inventory._id,color:'Blue',size:'M',qty:2,unitMinor:10000}]});
    const exchangeCommon={id:exchange.id,actor,roles:['support'],reason:'Replacement processed.',version:0};
    const received=await transitionReturn({...exchangeCommon,status:'received',restock:false});
    await assert.rejects(transitionReturn({...exchangeCommon,status:'replaced',version:received.version}),/courier and tracking/);
    const replacement={courier:'Test Courier',tracking:'REPLACE-123'};
    const concurrent=await Promise.allSettled([transitionReturn({...exchangeCommon,status:'replaced',version:received.version,replacement}),transitionReturn({...exchangeCommon,status:'replaced',version:received.version,replacement})]);
    assert.equal(concurrent.filter(result=>result.status==='fulfilled').length,1);
    assert.equal((await Inventory.findById(inventory.id)).stock,6);
    assert.equal((await Product.findById(product.id)).stock,6);
    assert.equal((await ReturnRequest.findById(exchange.id)).replacement.tracking,'REPLACE-123');
  }finally{
    await mongoose.disconnect();
    await replica.stop();
  }
});
