const {test}=require('node:test');
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const request=require('supertest');
const {MongoMemoryReplSet}=require('mongodb-memory-server');

test('Express and MongoDB foundation',async t=>{
  process.env.NODE_ENV='test';process.env.JWT_ACCESS_SECRET='test-access-secret-with-at-least-32-characters';process.env.OTP_HMAC_SECRET='test-otp-secret-with-at-least-32-characters';process.env.JWT_ISSUER='loveraf-test';
  const replica=await MongoMemoryReplSet.create({replSet:{count:1,storageEngine:'wiredTiger'}});process.env.MONGODB_URI=replica.getUri('loveraf_test');
  const {connectDatabase,disconnectDatabase}=require('../config/database');await connectDatabase();
  const deliveries={};const {createApplication}=require('../app');const runtime=createApplication({deliver:async message=>{deliveries[message.id]=message;}});const api=request(runtime.app);const {User}=require('../models/account.model');const {Media,Inventory}=require('../models/catalog.model');
  const call=(method,path,token,body,key)=>{let r=api[method](path);if(token)r=r.set('Authorization',`Bearer ${token}`);if(key)r=r.set('Idempotency-Key',key);if(body!==undefined)r=r.send(body);return r;};
  try{
    await t.test('liveness, database readiness and provider capabilities',async()=>{assert.equal((await api.get('/health/live')).status,200);const ready=await api.get('/health/ready');assert.equal(ready.status,200);assert.equal(ready.body.checks.mongodb,'connected');const features=await api.get('/api/v1/features');assert.equal(features.body.verification,false);assert.equal(features.body.media_upload,false);});
    const sellerRegistration=await call('post','/api/v1/auth/register',null,{name:'Seller One',email:'seller@example.test',phone:'01712345678',password:'CorrectLongPassword1'}),buyerRegistration=await call('post','/api/v1/auth/register',null,{name:'Buyer Two',email:'buyer@example.test',phone:'01812345678',password:'CorrectLongPassword2'});const sellerToken=sellerRegistration.body.token,buyerToken=buyerRegistration.body.token;
    await t.test('password and session authentication',async()=>{assert.equal(sellerRegistration.status,201);const stored=await User.findOne({email:'seller@example.test'}).select('+passwordHash');assert.notEqual(stored.passwordHash,'CorrectLongPassword1');assert.equal((await call('post','/api/v1/auth/login',null,{login:'seller@example.test',password:'wrong-password'})).status,401);assert.equal((await call('get','/api/v1/me',sellerToken)).body.email,'seller@example.test');});
    await t.test('OTP ownership, verification and administrator MFA',async()=>{const challenge=await call('post','/api/v1/auth/challenge',sellerToken,{channel:'email',purpose:'verify'});assert.equal(challenge.status,201);assert.equal((await call('post','/api/v1/auth/verify',buyerToken,{challengeId:challenge.body.challengeId,code:deliveries[challenge.body.challengeId].code})).status,400);assert.equal((await call('post','/api/v1/auth/verify',sellerToken,{challengeId:challenge.body.challengeId,code:deliveries[challenge.body.challengeId].code})).status,201);await User.updateOne({email:'seller@example.test'},{roles:['super_admin']});assert.equal((await call('get','/api/v1/admin/sellers',sellerToken)).status,403);const adminChallenge=await call('post','/api/v1/auth/challenge',sellerToken,{channel:'email',purpose:'admin'});await call('post','/api/v1/auth/verify',sellerToken,{challengeId:adminChallenge.body.challengeId,code:deliveries[adminChallenge.body.challengeId].code});assert.equal((await call('get','/api/v1/admin/sellers',sellerToken)).status,200);});
    const seller=await call('post','/api/v1/me/sellers',sellerToken,{name:'Store',handle:'store',category:'Men'});let productId,addressId;
    await t.test('seller and product require approval',async()=>{assert.equal(seller.status,201);const user=await User.findOne({email:'seller@example.test'});const media=await Media.create({owner:user._id,uri:'https://cdn.example.test/watch.png',mime:'image/png'});const product={title:'Smart Watch',description:'A verified product listing for integration tests.',category:'Men',sku:'WATCH-1',price:100.25,stock:10,sizes:['M','L'],images:[{id:String(media._id)}],variants:[{name:'Black',swatch:'#081426',imageIds:[String(media._id)]}],returnDays:3,exchangeDays:3,deliveryMinDays:2,deliveryMaxDays:3,codAvailable:true};assert.equal((await call('post',`/api/v1/me/sellers/${seller.body.id}/products`,sellerToken,product)).status,403);await call('patch',`/api/v1/admin/sellers/${seller.body.id}`,sellerToken,{status:'approved',reason:'Identity reviewed'});const created=await call('post',`/api/v1/me/sellers/${seller.body.id}/products`,sellerToken,product);assert.equal(created.status,201);productId=created.body.id;assert.equal((await call('get','/api/v1/products')).body.items.length,0);await call('patch',`/api/v1/admin/products/${productId}`,sellerToken,{status:'approved',version:created.body.version,reason:'Listing checked'});assert.equal((await call('get','/api/v1/products')).body.items.length,1);});
    await t.test('persistent address and idempotent variant cart',async()=>{const address=await call('post','/api/v1/me/addresses',buyerToken,{title:'Home',name:'Buyer',mobile:'01812345678',division:'Dhaka',district:'Dhaka',details:'House 10, Road 4',isDefault:true});assert.equal(address.status,201);addressId=address.body.id;const key=crypto.randomUUID(),line={productId,qty:2,color:'Black',size:'M'};assert.equal((await call('post','/api/v1/me/cart',buyerToken,line,key)).status,201);assert.equal((await call('post','/api/v1/me/cart',buyerToken,line,key)).status,201);const cart=await call('get','/api/v1/me/cart',buyerToken);assert.equal(cart.body.length,1);assert.equal(cart.body[0].qty,2);});
    await t.test('server quote, transaction order and retry protection',async()=>{const input={addressId,paymentMethod:'cod',promo:false};const quote=await call('post','/api/v1/checkout/quote',buyerToken,input);assert.equal(quote.body.totalMinor,20050);const key=crypto.randomUUID(),first=await call('post','/api/v1/orders',buyerToken,input,key),retry=await call('post','/api/v1/orders',buyerToken,input,key);assert.equal(first.status,201);assert.equal(retry.body.id,first.body.id);assert.equal((await call('get','/api/v1/me/cart',buyerToken)).body.length,0);assert.equal((await Inventory.findOne({product:productId,color:'Black',size:'M'})).reserved,2);assert.equal((await call('get',`/api/v1/orders/${first.body.id}`,sellerToken)).status,404);});
    await t.test('persistent chat membership and read state',async()=>{const conversation=await call('post','/api/v1/conversations',buyerToken,{kind:'support'});assert.equal(conversation.status,201);assert.equal((await call('post',`/api/v1/conversations/${conversation.body.id}/messages`,buyerToken,{body:'I need help.'})).status,201);assert.equal((await call('get',`/api/v1/conversations/${conversation.body.id}/messages`,sellerToken)).status,403);assert.equal((await call('post',`/api/v1/conversations/${conversation.body.id}/read`,buyerToken,{})).status,200);});
  }finally{await new Promise(resolve=>runtime.io.close(resolve));await disconnectDatabase();await replica.stop();}
});
